spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:postgresql://localhost:5432/blockchainAccounting
#    url: jdbc:postgresql://host.docker.internal:5432/blockchainAccounting
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: dev
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,health,info,beans,metrics,mappings
blockchainAccounting:
  app:
    jwtSecret: SUPERSECRETKEY
    jwtExpirationMs: 86400000


#spring:
#  mvc:
#    log-resolved-exception: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/blockchainAccounting
##    url: jdbc:postgresql://host.docker.internal:5432/blockchainAccounting
#    username: postgres
#    password: postgres
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: none
#  profiles:
#    active: test
#management:
#  endpoint:
#    env:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: env,health,info,beans,metrics,mappings
#blockchainAccounting:
#  app:
#    jwtSecret: SUPERSECRETKEY
#    jwtExpirationMs: 86400000
